title: Davidmogomezz
email: damagoza@gmail.com
description: >-
  Blog personal en donde compartire el desarrollo de aplicaciones web y moviles
  usando tecnologías en el backend como Ruby on Rails, Node Js y en el front
  Javascript con frameworks Vue, React y React Native. Usaremos bases de datos como
  Postgresql, Firebase, Supabase.
baseurl: ""
url: ""
twitter_username: davidmaogomezz
github_username:  davidmaogomezz

theme: minima
plugins:
  - jekyll-feed
